export const styles = {
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    backdropFilter: "blur(12px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: "#ffffff",
    borderRadius: "8px",
    width: "100%",
    maxWidth: "800px",
    maxHeight: "90vh",
    display: "flex",
    flexDirection: "column",
    boxShadow: "0 25px 50px -12px rgba(0,0,0,0.25)",
  },
  modalHeader: {
    padding: "20px 30px",
    borderBottom: "1px solid #e2e8f0",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modalTitle: {
    margin: 0,
    fontSize: "20px",
    color: "#0f172a",
    fontWeight: "bold",
  },
  closeBtn: {
    background: "transparent",
    border: "none",
    color: "#94a3b8",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  modalBody: {
    padding: "30px",
    overflowY: "auto",
    overflowX: "hidden",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  modalFooter: {
    padding: "20px 30px",
    borderTop: "1px solid #e2e8f0",
    display: "flex",
    justifyContent: "flex-end",
    gap: "15px",
  },
  btnCancel: {
    padding: "10px 20px",
    backgroundColor: "#ffffff",
    border: "1px solid #cbd5e1",
    borderRadius: "6px",
    color: "#334155",
    fontWeight: "bold",
    cursor: "pointer",
  },
  btnSave: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "10px 20px",
    backgroundColor: "#f97316",
    border: "none",
    borderRadius: "6px",
    color: "#ffffff",
    fontWeight: "bold",
    cursor: "pointer",
  },
  formGrid: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    width: "100%",
  },
  row3: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: "15px",
    width: "100%",
  },
  row2: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "15px",
    width: "100%",
    alignItems: "start",
  },
  inputGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    width: "100%",
  },
  label: {
    fontSize: "12px",
    fontWeight: "bold",
    color: "#374151",
    textTransform: "uppercase",
  },
  inputDisabled: {
    width: "100%",
    boxSizing: "border-box",
    padding: "10px",
    borderRadius: "6px",
    border: "1px solid #e2e8f0",
    backgroundColor: "#f3f4f6",
    color: "#6b7280",
    fontSize: "14px",
    fontWeight: "500",
  },
  input: {
    width: "100%",
    boxSizing: "border-box",
    padding: "10px",
    borderRadius: "6px",
    border: "1px solid #d1d5db",
    fontSize: "14px",
    color: "#111827",
    outline: "none",
  },
  textarea: {
    width: "100%",
    boxSizing: "border-box",
    padding: "10px",
    borderRadius: "6px",
    border: "1px solid #d1d5db",
    fontSize: "14px",
    color: "#111827",
    outline: "none",
    resize: "vertical",
  },
  fileInput: {
    width: "100%",
    boxSizing: "border-box",
    fontSize: "13px",
    color: "#4b5563",
  },
  inputGroupFull: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    width: "100%",
    boxSizing: "border-box",
  },
  selectBox: {
    width: "100%",
    minHeight: "160px",
    border: "2px dashed #cbd5e1",
    borderRadius: "8px",
    backgroundColor: "#ffffff",
    display: "flex",
    alignItems: "stretch",
    justifyContent: "stretch",
    boxSizing: "border-box",
    overflow: "hidden",
  },
  uploadButtonInvisible: {
    width: "100%",
    height: "100%",
    minHeight: "160px",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  placeholderContent: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    width: "100%",
    pointerEvents: "none",
  },
  selectBoxTitle: {
    display: "block",
    fontSize: "14px",
    fontWeight: "600",
    color: "#334155",
    margin: 0,
    textAlign: "center",
  },
  selectBoxSubtitle: {
    display: "block",
    fontSize: "12px",
    color: "#94a3b8",
    fontWeight: "400",
    textAlign: "center",
  },
  innerContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "20px",
    width: "100%",
    padding: "20px",
    boxSizing: "border-box",
  },
  previewContainer: {
    display: "flex",
    flexWrap: "wrap",
    gap: "14px",
    justifyContent: "center",
    width: "100%",
  },
  previewCard: {
    position: "relative",
    width: "110px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "6px",
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    padding: "6px",
    backgroundColor: "#ffffff",
    boxShadow: "0 1px 3px rgba(0,0,0,0.05)",
  },
  removeSingleBtn: {
    position: "absolute",
    top: "-6px",
    right: "-6px",
    backgroundColor: "#ef4444",
    border: "none",
    borderRadius: "50%",
    width: "22px",
    height: "22px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    boxShadow: "0 2px 4px rgba(0,0,0,0.2)",
    zIndex: 10,
  },
  previewImage: {
    width: "100%",
    height: "85px",
    objectFit: "cover",
    borderRadius: "6px",
  },
  previewName: {
    fontSize: "11px",
    color: "#374151",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    width: "100%",
    textAlign: "center",
  },
  actionsBar: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    flexWrap: "wrap",
    justifyContent: "center",
  },
  btnAddMore: {
    backgroundColor: "#ffffff",
    border: "1px solid #cbd5e1",
    borderRadius: "6px",
    padding: "0 16px",
    height: "42px",
    fontSize: "13px",
    fontWeight: "600",
    color: "#334155",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    boxSizing: "border-box",
  },
  btnClearAll: {
    backgroundColor: "#ffffff",
    border: "1px solid #fca5a5",
    borderRadius: "6px",
    padding: "0 16px",
    height: "42px",
    fontSize: "13px",
    fontWeight: "600",
    color: "#dc2626",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    boxSizing: "border-box",
  },
};